### ISSUE TITLE
Statistics API V2

### ISSUE THREAD

**Issue by MatteoGauthier** [MatteoGauthier/active-users-widget#14]
- [x] Summary
   - [x] Most popular country #23 
   - [x] Total views (not 30 days) #23 
   - [x] Last 30 days views #23
- [x] Values
   - [x] Formatted data #23

**Comment by MatteoGauthier** [comment]
Fix #23
